sudo: false
language: ruby
rvm: 2.6.6
cache: bundler
install:
  - bundle install --without production --retry=6
  - bundle exec rake db:setup
script:
  - bundle exec rake
notifications:
  email: false
